"""Add providers table

Revision ID: 2f052feada5b
Revises: 7a51a5bf8fc9
Create Date: 2025-05-27 22:41:55.078010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f052feada5b'
down_revision: Union[str, None] = '7a51a5bf8fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'longitude')
    op.drop_column('providers', 'latitude')
    # ### end Alembic commands ###
