"""Add availability and bookings

Revision ID: 6b67dbc63ba9
Revises: 4b4071702e7d
Create Date: 2025-05-29 01:40:45.136357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b67dbc63ba9'
down_revision: Union[str, None] = '4b4071702e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('services')
    op.drop_table('bookings')
    op.drop_table('provider_availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_availability',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('provider_availability_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_availability_pkey'))
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('bookings_client_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('bookings_provider_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('bookings_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('popular', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('services_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    # ### end Alembic commands ###
